apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orcasio/springboot-example-config.git
    targetRevision: qa
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: springboot-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
